In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *
import pyspark
import pandas as pd
import os
import requests
from datetime import datetime
from urllib.parse import quote

In [2]:
#Oracle
spark=SparkSession \
    .builder.master("local[*]") \
    .appName("SparkandOracledbTest") \
    .config("spark.jars", "jars/ojdbc8.jar") \
    .getOrCreate()

23/02/20 02:28:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [ ]:
df = spark.createDataFrame(pd.read_json("http://engineer.da.co.th/api_json.php?all"))

In [3]:
df=spark.read.format("jdbc") \
        .option("driver","oracle.jdbc.driver.OracleDriver") \
        .option("url","jdbc:oracle:thin:@192.168.10.22:1521/xe") \
        .option("dbtable",'NOOK."data"') \
        .option("user","system") \
        .option("password","softnixteam") \
        .load()
df.toPandas()

23/02/20 02:28:52 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

,task_id,dag_id,run_id,start_date,end_date,duration,state,try_number,hostname,unixname,...,pid,max_tries,executor_config,pool_slots,queued_by_job_id,external_executor_id,trigger_id,trigger_timeout,next_method,next_kwargs
0,LoadtoHive,telemetering_stations,scheduled__2022-08-30T10:00:00+00:00,30/8/2022 10:15:49.431311+00,30/8/2022 10:15:51.893139+00,2.461828,success,1,Airflow1,root,...,71441,1,gAV9lC4=,1,2,None,None,None,None,null
1,RemoveTmp,early_warning_status,scheduled__2022-09-20T09:18:00+00:00,20/9/2022 09:33:20.524631+00,20/9/2022 09:33:20.524631+00,0,skipped,0,None,root,...,None,1,gAV9lC4=,1,None,None,None,None,None,null
2,backup_data_schema,hive_data_backup,scheduled__2022-08-29T10:00:00+00:00,30/8/2022 10:00:01.537461+00,30/8/2022 10:16:09.055564+00,967.518103,success,1,Airflow1,root,...,240326,1,gAV9lC4=,1,2,None,None,None,None,null
3,pythonChagetoCSV,early_warning_status,scheduled__2022-08-30T10:03:00+00:00,30/8/2022 10:18:15.738998+00,30/8/2022 10:18:18.098593+00,2.359595,success,1,Airflow1,root,...,83335,1,gAV9lC4=,1,2,None,None,None,None,null
4,log_datetime,hive_data_backup,scheduled__2022-08-29T10:00:00+00:00,30/8/2022 10:16:09.923257+00,30/8/2022 10:16:10.09634+00,0.173083,success,1,Airflow1,root,...,73119,1,gAV9lC4=,1,2,None,None,None,None,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166467,load_to_noti,telemetering_stations,scheduled__2022-08-30T10:00:00+00:00,30/8/2022 10:15:38.581248+00,30/8/2022 10:15:42.413849+00,3.832601,success,1,Airflow1,root,...,69900,1,gAV9lC4=,1,2,None,None,None,None,null
166468,RemoveTmp,noise_api,scheduled__2022-08-30T10:00:00+00:00,30/8/2022 10:15:42.435918+00,30/8/2022 10:15:42.909809+00,0.473891,success,1,Airflow1,root,...,70464,1,gAV9lC4=,1,2,None,None,None,None,null
166469,RemoveTmp,early_warning_vill,scheduled__2022-08-30T10:00:00+00:00,30/8/2022 10:15:43.244157+00,30/8/2022 10:15:43.47428+00,0.230123,success,1,Airflow1,root,...,70624,1,gAV9lC4=,1,2,None,None,None,None,null
166470,RemoveTmp,view_air_quality_factor_2,scheduled__2022-08-30T10:00:00+00:00,30/8/2022 10:15:48.464997+00,30/8/2022 10:15:48.865592+00,0.400595,success,1,Airflow1,root,...,71318,1,gAV9lC4=,1,2,None,None,None,None,null
166471,hive_sql,telemetering_stations,scheduled__2022-08-30T10:00:00+00:00,30/8/2022 10:15:57.799547+00,30/8/2022 10:17:27.248406+00,89.448859,success,1,Airflow1,root,...,72237,1,gAV9lC4=,1,2,None,None,None,None,null

In [ ]:
df.write \
  .format("jdbc") \
  .option("driver","oracle.jdbc.driver.OracleDriver") \
  .option("url","jdbc:oracle:thin:@192.168.10.22:1521/xe") \
  .option("dbtable", "NOOK.engineer") \
  .option("user", "system") \
  .option("password", "softnixteam") \
  .save()